module.exports.SAVE_FRIDGE_INGREDIENT_EVENT = 'SAVE_FRIDGE_INGREDIENT';
module.exports.MARK_COMPLETE_GROCERY_ITEM_EVENT = 'MARK_ITEM_COMPLETE';
module.exports.SAVE_OR_UPDATE_MANY_GROCERY_ITEMS_EVENT =
  'SAVE_OR_UPDATE_MANY_ITEMS';
module.exports.DELETE_RECIPE = 'DELETE_RECIPE';
